config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    member do
      post :add_like
      post :reply_tweet
    end
  end
  devise_for :users
  resources :users do
    member do
      get :followers
      get :following
    end
    collection do
      get :follow
      get :unfollow
      get :retweet
    end
  end
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :replied_tweets, class_name:  "Tweet",
                                 foreign_key: "tweet_id",
                                 dependent:   :destroy
  has_many :attachments, as: :attachable
  accepts_nested_attributes_for :attachments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "following_id",
                                 dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :tweets
  enum gender: [:male, :female]
  has_many :attachments, as: :attachable
  accepts_nested_attributes_for :attachments

  has_attached_file :profile_pic, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = current_user.following.map{|a| a.tweets}.flatten
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  def add_like
    @tweet = Tweet.find(params[:id])
    puts params[:type][:type]
    if params[:type][:type] == 'add'
      @tweet.likes.create(liked_by: current_user.id)
    else
      @tweet.likes.where(liked_by: current_user.id).all.destroy_all
    end
    @tweets = Tweet.all
    render partial: 'users/tweets_list', locals: {tweets: @tweets}
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save!
        format.html { redirect_to users_path(current_user), notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { redirect_to users_path(current_user) }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:type, :message, :user_id, :tweet_id, :attachable, :picture, attachments_attributes: [:id, :picture, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :followers, :following]

  # GET /Users
  # GET /Users.json
  def index
    @users = User.all
  end

  # GET /Users/1
  # GET /Users/1.json
  def show
    @tweet = Tweet.new
    @tweets = @user.tweets.all
  end

  # GET /Users/new
  def new
    @user = User.new
  end

  # GET /Users/1/edit
  def edit
  end

  def followers
    @user = User.find()
    @tweet = Tweet.new
  end

  def following
    @tweet = Tweet.new
  end

  def follow
    Relationship.create!(following_id: params[:id][:id], follower_id: current_user.id)
    redirect_to users_path
  end

  def unfollow
    Relationship.where(following_id: params[:id][:id], follower_id: current_user.id).destroy_all
    redirect_to users_path
  end

  def retweet
    @tweet = Tweet.find(params[:id][:id])
    Tweet.create(message: @tweet.message, user_id: current_user.id)
    redirect_to users_path(current_user.id)
  end

  # POST /Users
  # POST /Users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Users/1
  # PATCH/PUT /Users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Users/1
  # DELETE /Users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
       params.require(:user).permit(:name, :age, :gender, :profile_pic, attachments_attributes: [:id, :picture, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SynupTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.slim
= simple_form_for(@tweet) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/tweets/edit.html.slim
h1 Editing tweet

== render 'form'

=> link_to 'Show', @tweet
'|
=< link_to 'Back', tweets_path

app/views/tweets/index.html.slim
h1 Listing tweets
.row
  .col-md-6
    .tweets_list
      - @tweets.each do |tweet|
        .tweets-box
          = tweet.message
          | by
          = link_to tweet.user.name, users_path(tweet.user)
          .row
            .col-md-3
              = tweet.likes.count
              - unless tweet.likes.where(liked_by: current_user.id).present?
                button.btn-sm.change_like data-id='#{tweet.id}' data-type='add' Like
              - else
                button.btn-sm.change_like data-id='#{tweet.id}' data-type='delete' Unlike
            .col-md-3
              button.btn-sm.reply_tweet data-id='#{tweet.id}' Reply
            .col-md-3
              button.btn-sm.retweet data-id='#{tweet.id}' Retweet

app/views/tweets/new.html.slim
h1 New tweet

== render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_tweet_path(@tweet)
'|
=< link_to 'Back', tweets_path

app/views/users/_attachment_fields.html.slim
.nested-fields
  = f.input :picture, as: :file
  = f.input :attachable_id, value: 1
  = f.input :attachable_type, value: 'Tweet'
  = link_to_remove_association "remove picture", f

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :age
    = f.input :gender, collection:[:male, :female]
    = f.input :profile_pic, as: :file

  .form-actions
    = f.button :submit

app/views/users/_new_tweet.html.slim
= simple_form_for(@tweet) do |f|
  = f.error_notification
  .form-inputs
    = f.input :message
    = f.hidden_field :user_id, value: current_user.id
    = f.fields_for :attachable do |photo|
      = photo.file_field :picture

  .form-actions
    = f.button :submit

app/views/users/_show_user.html.slim
.container
  .row
    .col-md-3.col-md-offest-3
      h4 Username :
      = @user.name
      h4 Age:
      = @user.age
      h4 Gender:
      = @user.gender
    .col-md-3
      h4 Profile pic:
      = image_tag @user.profile_pic.url(:thumb)
      br
      br
      = link_to 'Edit bio', edit_user_path(@user), class: 'btn-sm btn-default'
      = link_to 'Logout', destroy_user_session_path, method: :delete
  br

  .row
    .col-md-3
      = link_to 'Followers', followers_user_path(@user)
      br
      = @user.followers.count
    .col-md-3
      = link_to 'Following', following_user_path(@user)
      br
      = @user.following.count
    .col-md-3
      h6 Tweet count
      = @user.tweets.count

  br
  br
  .row
    .col-md-4
      h5 Listing tweets
      = render 'new_tweet'
      .tweets_list
        = render 'tweets_list'

app/views/users/_tweet_box.html.slim
.div id="tweets-box-#{tweet.id}"
  .tweets-box
    = tweet.message
    .row
      .col-md-3
        = tweet.likes.count
        - unless tweet.likes.where(liked_by: current_user.id).present?
          button.btn-sm.change_like data-id='#{tweet.id}' data-type='add' Like
        - else
          button.btn-sm.change_like data-id='#{tweet.id}' data-type='delete' Unlike
      .col-md-3
        button.btn-sm.reply_tweet data-id='#{tweet.id}' Reply
      .col-md-3
        button.btn-sm.retweet data-id='#{tweet.id}' Retweet

app/views/users/_tweets_list.html.slim
- @tweets.each do |tweet|
  .div id="tweets-box-#{tweet.id}"
    .tweets-box
      = tweet.message
      - if tweet.attachments.present?
        - tweet.attachments.each do |pic|
          = image_tag pic.picture
      .row
        .col-md-3
          = tweet.likes.count
          - unless tweet.likes.where(liked_by: current_user.id).present?
            button.btn-sm.change_like data-id='#{tweet.id}' data-type='add' Like
          - else
            button.btn-sm.change_like data-id='#{tweet.id}' data-type='delete' Unlike
        .col-md-3
          button.btn-sm.reply_tweet data-id='#{tweet.id}' Reply
          .show_it id="show-#{tweet.id}"
            h6 Reply Tweet
            = simple_form_for(@tweet) do |f|
              = f.error_notification
              .form-inputs
                = f.input :message
                = f.hidden_field :user_id, value: current_user.id
                = f.hidden_field :tweet_id, value: tweet.id
                = f.fields_for :attachments, @tweet.attachments.build do |photo|
                  = photo.file_field :picture

              .form-actions
                = f.button :submit
        .col-md-3
          button.btn-sm.retweet data-id='#{tweet.id}' Retweet
      .row
        - if tweet.replied_tweets.present?
          h6 Replied Tweets
          - tweet.replied_tweets.each do |tweet|
            .row
              br
              = tweet.message

app/views/users/edit.html.slim
h1 Editing Bio

== render 'form'

br

=> link_to 'Show', @user

app/views/users/followers.html.slim
= render 'show_user_list'

app/views/users/following.html.slim
= render 'show_user_list'

app/views/users/index.html.slim
h1 Listing users
.row
  .col-md-6
    .users_list
      - @users.each do |user|
        .users-box
          = user.name
          .row
            .col-md-3
              - if Relationship.where(following_id: user.id, follower_id: current_user.id).present?
                button.btn-sm.unfollow data-id='#{user.id}' Unfollow
              - else
                button.btn-sm.follow data-id='#{user.id}' Follow

app/views/users/show.html.slim
= render 'show_user'